### ISSUE TITLE
How are wrap-around axes handled in Coverage.subsetByValue?

### ISSUE THREAD

**Issue by letmaik** [Reading-eScience-Centre/coverage-jsapi#6]
When an axis is a wrap-around axis like longitude then it may lead to surprising behaviour if this fact is ignored when doing `cov.subsetByValue({x: {target: -179} })` and getting a subsetted x axis with x value -150 for example, even though there was a closer axis value on the other side, like 179.

Does a CRS define whether an axis is a wrap-around one?

**Comment by jonblower** [comment]
I'm not sure, but I think it's only longitude axes that behave in this way. But note that the longitude does not have to be true geographic longitude: there are other spherical systems (notably rotated-pole systems) that would employ longitude axes.

I'm not sure how you would detect these reliably. It may be enough for 95% of cases to look for geographic longitude in CRS84 or EPSG4326.

**Comment by letmaik** [comment]
Hm, when thinking about it, it's also projections to some degree. If your query is "get me the geographically closest point to those CRS coordinates" then it applies in one way or another as well, just not as cleanly as a simple wrapped around longitude axis.
Maybe the solution then is to not include that kind of semantics in the definition of what a "target" query should do, but just define it mathematically in terms of closest numeric value. If clients need more than that they could check "the other side" and see if that point is closer. Because then you already assume geographic distances etc. which for arbitrary axes is not always the case.

**Comment by jonblower** [comment]
Yeah, you could do true nearest-neighbour in terms of great circle distance. It might not even be too computationally intensive, because the "mathematical nearest neighbour" would be a pretty good guess and you could just search around that point. But I think it's overkill for now.

**Comment by letmaik** [comment]
Ok closing this, I think it's a job for a higher-level library that would then use Coverage.subsetByIndex after figuring out the geographically closest coordinates (and with that axis indices) itself.
